name: "I have issues"

description: "consume the output of the previous action and create a new issue in the repository"

inputs:
    joke:
        description: "This will become the body of the created issue"
    issue-title:
        description: "Every issue needs a title, it's nice to suppy one, even though you could do thid dynamically within your code"
        default: "a joke for you"
        required: true

runs:
    using: "node12"
    main: "index.js"